# tomcat配置
server:
  port: 8080
# 数据源
datasource:
  password: ********
  user: ********
  driverClass: com.mysql.jdbc.Driver
  jdbcUrl: ********
  # 初始化连接池中的连接数，取值应在minPoolSize与maxPoolSize之间，默认为3
  initialPoolSize: 15
  # 最大空闲时间，60秒内未使用则连接被丢弃。若为0则永不丢弃。默认值: 0
  maxIdleTime: 0
  # 连接池中保留的最大连接数。默认值: 15
  maxPoolSize: 100
  # 连接池中保留的最小连接数，默认为：3
  minPoolSize: 10
  # c3p0全局的PreparedStatements缓存的大小。
  # 如果maxStatements与maxStatementsPerConnection均为0，则缓存不生效，只要有一个不为0，则语句的缓存就能生效。如果默认值: 0
  maxStatements: 200
  # 当连接池连接耗尽时，客户端调用getConnection()后等待获取新连接的时间，超时后将抛出SQLException，如设为0则无限期等待。单位毫秒。默认: 0
  checkoutTimeout: 3000
# mybatis配置
mybatis:
  # 映射文件路径
  mapper-locations: classpath:com/tml/mapper/**/*.xml
  # mybatis配置文件路径
  # config-location: classpath:mybatis-config.xml
# logback配置
logging:
  config: classpath:logback.xml
# 时间格式化
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
